from graph import Graph
from scipy import stats
import numpy as np
import itertools
import math
import sys
import os as os
import cPickle as pickle
from matplotlib import pyplot as plt
import seaborn




dir_current = os.getcwd()
dir_name = dir_current + '/figure'

# set up figure
fig = plt.figure()
#ax = fig.add_subplot(111)
ft = 15 # tick font size
fl = 16 # label font size
fs_s = 12 # small text font size
ms = 5 # marker size
lw = 3 # line width size



"""
This code shows how to use BP (sum-product alg)+ gradient ascent opt. to 
get the marginals of each kinases. 

New IC:  Ebind[0,:] = np.array([-5,-3,-3,-3]) 
original IC : Ebind[0,:] = np.array([-1,-2,-1,-1.5])

New omega" omega3 = 2, omegarest = 8 (i.e. freq3 =0.5, freqrest =0.125)
original omega: all omega = 4


"""




def conditional_prob_on(PAstate, Ematrix, Wbind, omega):
	
	"""
	The conditional prob is dependent on the biophysical model

	"""
	if isinstance(omega, float):
		omega = np.array([omega])

	omegainv= omega**-1
	num = 0.0
	den = 0.0
	


	for j in range(0,len(Ematrix)):
		num = num + omegainv[j]*np.exp(-Ematrix[j])*PAstate[j]
		den = den + omegainv[j]*(np.exp(-Ematrix[j])*PAstate[j] + np.exp(-Wbind)*(1-PAstate[j]))
	
	return num / (1 + den)



"""
get_mn_log_likelihood() function is not used in this program

"""
def get_mn_log_likelihood(obs,probs):
	""" Return the (log)likelihood of obs, given the probs"""
	# Multinomial Distribution Log PMF
	# ln (pdf)      =             multinomial coeff            *   product of probabilities
	# ln[f(x|n, p)] = [ln(n!) - (ln(x1!)+ln(x2!)+...+ln(xk!))] + [x1*ln(p1)+x2*ln(p2)+...+xk*ln(pk)]     

	multinomial_coeff_denom= 0
	prod_probs = 0
	for x in range(0,len(obs)): # loop through state counts in each observation
		multinomial_coeff_denom = multinomial_coeff_denom + math.log(math.factorial(obs[x]))
		prod_probs = prod_probs + obs[x]*math.log(probs[x])
	 
	multinomial_coeff = math.log(math.factorial(sum(obs))) -  multinomial_coeff_denom
	likelihood = multinomial_coeff + prod_probs
	return likelihood


def sample_generate(margDist, Nsamples):
	""" margDist is a 2-tuple of len(margDist)
		This functions returns a sample of data generated by the marg prob specified
	"""
	xk = np.arange(2)
	margsamples = np.zeros([len(margDist), Nsamples]) 
	for tupleindex in xrange(len(margDist)):
		custm = stats.rv_discrete(name='custm', values=(xk, margDist[tupleindex]))
		margsamples[tupleindex, :]= custm.rvs(size= Nsamples)

	return margsamples


def InfoMaxGD(P1, P2, P126, P67joint, P3456, P123, P124, P125, bindingE, bindingW, oall, regC):

	nabla_E = np.zeros(len(bindingE))
	underflowcutoff = 0.001


	freqall= oall**-1
	delP3_12_1 = np.zeros((2,2,2), dtype = float)
	delP3_12_2 = np.zeros((2,2,2), dtype = float)
	delP4_12_1 = np.zeros((2,2,2), dtype = float)
	delP4_12_2 = np.zeros((2,2,2), dtype = float)
	delP5_12_1 = np.zeros((2,2,2), dtype = float)
	delP5_12_2 = np.zeros((2,2,2), dtype = float)
	delP6_345_3 = np.zeros((2,2,2,2), dtype = float)
	delP6_345_4 = np.zeros((2,2,2,2), dtype = float)
	delP6_345_5 = np.zeros((2,2,2,2), dtype = float)
	delP7_345_3 = np.zeros((2,2,2,2), dtype = float)
	delP7_345_4 = np.zeros((2,2,2,2), dtype = float)
	delP7_345_5 = np.zeros((2,2,2,2), dtype = float)
	delf612_13 = np.zeros((2,2,2), dtype = float)
	delf612_23 = np.zeros((2,2,2), dtype = float)
	delf612_14 = np.zeros((2,2,2), dtype = float)
	delf612_24 = np.zeros((2,2,2), dtype = float)
	delf612_15 = np.zeros((2,2,2), dtype = float)
	delf612_25 = np.zeros((2,2,2), dtype = float)
	delf612_36 = np.zeros((2,2,2), dtype = float)
	delf612_46 = np.zeros((2,2,2), dtype = float)
	delf612_56 = np.zeros((2,2,2), dtype = float)

	delf712_13 = np.zeros((2,2,2), dtype = float)
	delf712_23 = np.zeros((2,2,2), dtype = float)
	delf712_14 = np.zeros((2,2,2), dtype = float)
	delf712_24 = np.zeros((2,2,2), dtype = float)
	delf712_15 = np.zeros((2,2,2), dtype = float)
	delf712_25 = np.zeros((2,2,2), dtype = float)
	delf712_37 = np.zeros((2,2,2), dtype = float)
	delf712_47 = np.zeros((2,2,2), dtype = float)
	delf712_57 = np.zeros((2,2,2), dtype = float)



	for tstep in xrange(1):




		# bindingE[i]: i = 0, 1 (E31, E32, ngb of 3)
		#			       2, 3 (E41, E42, nbg of 4)
		#				   4, 5 (E51, E52, nbg of 5)
		#				   6, 7,  8  (E63, E64, E65, nbg of 6)
		#				   9, 10, 11 (E73, E74, E75, nbg of 7)

		

		# First calculate delP3_12_x
		delP3_12_1[1,0,0] = (-freqall[0]*np.exp(-bindingE[0])*0.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*0.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[0])*0.0
				+freqall[1]*np.exp(-bindingE[1])*0.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*0.0))**2)


		delP3_12_1[1,1,0] = (-freqall[0]*np.exp(-bindingE[0])*1*(1
				+(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*0.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[0])*1.0
				+freqall[1]*np.exp(-bindingE[1])*0.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*0.0))**2)


		delP3_12_1[1,0,1] = (-freqall[0]*np.exp(-bindingE[0])*0.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*1.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[0])*0.0
				+freqall[1]*np.exp(-bindingE[1])*1.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*1.0))**2)


		delP3_12_1[1,1,1] = (-freqall[0]*np.exp(-bindingE[0])*1.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*1.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[0])*1.0
				+freqall[1]*np.exp(-bindingE[1])*1.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*1.0))**2)


		delP3_12_1[0,:,:] = 1- delP3_12_1[1,:,:]




		delP3_12_2[1,0,0] = (-freqall[1]*np.exp(-bindingE[1])*0.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*0.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[0])*0.0
				+freqall[1]*np.exp(-bindingE[1])*0.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*0.0))**2)


		delP3_12_2[1,0,1] = (-freqall[1]*np.exp(-bindingE[1])*1*(1
				+(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*1.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[0])*0.0
				+freqall[1]*np.exp(-bindingE[1])*1.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*1.0))**2)


		delP3_12_2[1,1,0] = (-freqall[1]*np.exp(-bindingE[1])*0.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*0.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[0])*1.0
				+freqall[1]*np.exp(-bindingE[1])*0.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*0.0))**2)


		delP3_12_2[1,1,1] = (-freqall[1]*np.exp(-bindingE[1])*1.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*1.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[0])*1.0
				+freqall[1]*np.exp(-bindingE[1])*1.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*1.0))**2)


		delP3_12_2[0,:,:] = 1- delP3_12_2[1,:,:]



		# Below calculate delP4_12_x
		# reminder: bindingE[i]: i= 2, 3 (E41, E42, nbg of 4)

		delP4_12_1[1,0,0] = (-freqall[0]*np.exp(-bindingE[2])*0.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*0.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[2])*0.0
				+freqall[1]*np.exp(-bindingE[3])*0.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*0.0))**2)


		delP4_12_1[1,1,0] = (-freqall[0]*np.exp(-bindingE[2])*1*(1
				+(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*0.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[2])*1.0
				+freqall[1]*np.exp(-bindingE[3])*0.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*0.0))**2)


		delP4_12_1[1,0,1] = (-freqall[0]*np.exp(-bindingE[2])*0.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*1.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[2])*0.0
				+freqall[1]*np.exp(-bindingE[3])*1.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*1.0))**2)


		delP4_12_1[1,1,1] = (-freqall[0]*np.exp(-bindingE[2])*1.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*1.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[2])*1.0
				+freqall[1]*np.exp(-bindingE[3])*1.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*1.0))**2)


		delP4_12_1[0,:,:] = 1- delP4_12_1[1,:,:]




		delP4_12_2[1,0,0] = (-freqall[1]*np.exp(-bindingE[3])*0.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*0.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[2])*0.0
				+freqall[1]*np.exp(-bindingE[3])*0.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*0.0))**2)


		delP4_12_2[1,0,1] = (-freqall[1]*np.exp(-bindingE[3])*1*(1
				+(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*1.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[2])*0.0
				+freqall[1]*np.exp(-bindingE[3])*1.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*1.0))**2)


		delP4_12_2[1,1,0] = (-freqall[1]*np.exp(-bindingE[3])*0.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*0.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[2])*1.0
				+freqall[1]*np.exp(-bindingE[3])*0.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*0.0))**2)


		delP4_12_2[1,1,1] = (-freqall[1]*np.exp(-bindingE[3])*1.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*1.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[2])*1.0
				+freqall[1]*np.exp(-bindingE[3])*1.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*1.0))**2)


		delP4_12_2[0,:,:] = 1- delP4_12_2[1,:,:]




		# Below calculate delP5_12_x
		# reminder: bindingE[i]: i= 4, 5 (E51, E52, nbg of 5)

		delP5_12_1[1,0,0] = (-freqall[0]*np.exp(-bindingE[4])*0.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*0.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[4])*0.0
				+freqall[1]*np.exp(-bindingE[5])*0.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*0.0))**2)


		delP5_12_1[1,1,0] = (-freqall[0]*np.exp(-bindingE[4])*1*(1
				+(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*0.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[4])*1.0
				+freqall[1]*np.exp(-bindingE[5])*0.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*0.0))**2)


		delP5_12_1[1,0,1] = (-freqall[0]*np.exp(-bindingE[4])*0.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*1.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[4])*0.0
				+freqall[1]*np.exp(-bindingE[5])*1.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*1.0))**2)


		delP5_12_1[1,1,1] = (-freqall[0]*np.exp(-bindingE[4])*1.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*1.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[4])*1.0
				+freqall[1]*np.exp(-bindingE[5])*1.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*1.0))**2)


		delP5_12_1[0,:,:] = 1- delP5_12_1[1,:,:]




		delP5_12_2[1,0,0] = (-freqall[1]*np.exp(-bindingE[5])*0.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*0.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[4])*0.0
				+freqall[1]*np.exp(-bindingE[5])*0.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*0.0))**2)


		delP5_12_2[1,0,1] = (-freqall[1]*np.exp(-bindingE[5])*1*(1
				+(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*1.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[4])*0.0
				+freqall[1]*np.exp(-bindingE[5])*1.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*0.0-freqall[1]*1.0))**2)


		delP5_12_2[1,1,0] = (-freqall[1]*np.exp(-bindingE[5])*0.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*0.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[4])*1.0
				+freqall[1]*np.exp(-bindingE[5])*0.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*0.0))**2)


		delP5_12_2[1,1,1] = (-freqall[1]*np.exp(-bindingE[5])*1.0*(1
				+(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*1.0)*np.exp(-bindingW)))/((1
				+freqall[0]*np.exp(-bindingE[4])*1.0
				+freqall[1]*np.exp(-bindingE[5])*1.0
				+np.exp(-bindingW)*(freqall[0]+freqall[1]-freqall[0]*1.0-freqall[1]*1.0))**2)


		delP5_12_2[0,:,:] = 1- delP5_12_2[1,:,:]


		delP6_345_3[1,0,0,0] = (-freqall[2]*np.exp(-bindingE[6])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*0.0
				+freqall[3]*np.exp(-bindingE[7])*0.0
				+freqall[4]*np.exp(-bindingE[8])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*0.0))**2)

		delP6_345_3[1,1,0,0] = (-freqall[2]*np.exp(-bindingE[6])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*1.0
				+freqall[3]*np.exp(-bindingE[7])*0.0
				+freqall[4]*np.exp(-bindingE[8])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*0.0))**2)

		delP6_345_3[1,0,1,0] = (-freqall[2]*np.exp(-bindingE[6])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*0.0
				+freqall[3]*np.exp(-bindingE[7])*1.0
				+freqall[4]*np.exp(-bindingE[8])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*0.0))**2)

		delP6_345_3[1,0,0,1] = (-freqall[2]*np.exp(-bindingE[6])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*0.0
				+freqall[3]*np.exp(-bindingE[7])*0.0
				+freqall[4]*np.exp(-bindingE[8])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*1.0))**2)

		delP6_345_3[1,1,1,0] = (-freqall[2]*np.exp(-bindingE[6])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*1.0
				+freqall[3]*np.exp(-bindingE[7])*1.0
				+freqall[4]*np.exp(-bindingE[8])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*0.0))**2)

		delP6_345_3[1,1,0,1] = (-freqall[2]*np.exp(-bindingE[6])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*1.0
				+freqall[3]*np.exp(-bindingE[7])*0.0
				+freqall[4]*np.exp(-bindingE[8])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*1.0))**2)

		delP6_345_3[1,0,1,1] = (-freqall[2]*np.exp(-bindingE[6])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*0.0
				+freqall[3]*np.exp(-bindingE[7])*1.0
				+freqall[4]*np.exp(-bindingE[8])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*1.0))**2)

		delP6_345_3[1,1,1,1] = (-freqall[2]*np.exp(-bindingE[6])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*1.0
				+freqall[3]*np.exp(-bindingE[7])*1.0
				+freqall[4]*np.exp(-bindingE[8])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*1.0))**2)

		delP6_345_3[0,:,:,:] = 1- delP6_345_3[1,:,:,:]

		###
		###
		delP6_345_4[1,0,0,0] = (-freqall[3]*np.exp(-bindingE[7])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*0.0
				+freqall[3]*np.exp(-bindingE[7])*0.0
				+freqall[4]*np.exp(-bindingE[8])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*0.0))**2)

		delP6_345_4[1,1,0,0] = (-freqall[3]*np.exp(-bindingE[7])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*1.0
				+freqall[3]*np.exp(-bindingE[7])*0.0
				+freqall[4]*np.exp(-bindingE[8])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*0.0))**2)

		delP6_345_4[1,0,1,0] = (-freqall[3]*np.exp(-bindingE[7])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*0.0
				+freqall[3]*np.exp(-bindingE[7])*1.0
				+freqall[4]*np.exp(-bindingE[8])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*0.0))**2)

		delP6_345_4[1,0,0,1] = (-freqall[3]*np.exp(-bindingE[7])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*0.0
				+freqall[3]*np.exp(-bindingE[7])*0.0
				+freqall[4]*np.exp(-bindingE[8])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*1.0))**2)

		delP6_345_4[1,1,1,0] = (-freqall[3]*np.exp(-bindingE[7])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*1.0
				+freqall[3]*np.exp(-bindingE[7])*1.0
				+freqall[4]*np.exp(-bindingE[8])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*0.0))**2)

		delP6_345_4[1,1,0,1] = (-freqall[3]*np.exp(-bindingE[7])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*1.0
				+freqall[3]*np.exp(-bindingE[7])*0.0
				+freqall[4]*np.exp(-bindingE[8])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*1.0))**2)

		delP6_345_4[1,0,1,1] = (-freqall[3]*np.exp(-bindingE[7])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*0.0
				+freqall[3]*np.exp(-bindingE[7])*1.0
				+freqall[4]*np.exp(-bindingE[8])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*1.0))**2)

		delP6_345_4[1,1,1,1] = (-freqall[3]*np.exp(-bindingE[7])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*1.0
				+freqall[3]*np.exp(-bindingE[7])*1.0
				+freqall[4]*np.exp(-bindingE[8])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*1.0))**2)

		delP6_345_4[0,:,:,:] = 1- delP6_345_4[1,:,:,:]


		delP6_345_5[1,0,0,0] = (-freqall[4]*np.exp(-bindingE[8])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*0.0
				+freqall[3]*np.exp(-bindingE[7])*0.0
				+freqall[4]*np.exp(-bindingE[8])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*0.0))**2)

		delP6_345_5[1,1,0,0] = (-freqall[4]*np.exp(-bindingE[8])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*1.0
				+freqall[3]*np.exp(-bindingE[7])*0.0
				+freqall[4]*np.exp(-bindingE[8])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*0.0))**2)

		delP6_345_5[1,0,1,0] = (-freqall[4]*np.exp(-bindingE[8])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*0.0
				+freqall[3]*np.exp(-bindingE[7])*1.0
				+freqall[4]*np.exp(-bindingE[8])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*0.0))**2)

		delP6_345_5[1,0,0,1] = (-freqall[4]*np.exp(-bindingE[8])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*0.0
				+freqall[3]*np.exp(-bindingE[7])*0.0
				+freqall[4]*np.exp(-bindingE[8])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*1.0))**2)

		delP6_345_5[1,1,1,0] = (-freqall[4]*np.exp(-bindingE[8])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*1.0
				+freqall[3]*np.exp(-bindingE[7])*1.0
				+freqall[4]*np.exp(-bindingE[8])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*0.0))**2)

		delP6_345_5[1,1,0,1] = (-freqall[4]*np.exp(-bindingE[8])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*1.0
				+freqall[3]*np.exp(-bindingE[7])*0.0
				+freqall[4]*np.exp(-bindingE[8])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*1.0))**2)

		delP6_345_5[1,0,1,1] = (-freqall[4]*np.exp(-bindingE[8])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*0.0
				+freqall[3]*np.exp(-bindingE[7])*1.0
				+freqall[4]*np.exp(-bindingE[8])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*1.0))**2)

		delP6_345_5[1,1,1,1] = (-freqall[4]*np.exp(-bindingE[8])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[6])*1.0
				+freqall[3]*np.exp(-bindingE[7])*1.0
				+freqall[4]*np.exp(-bindingE[8])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*1.0))**2)

		delP6_345_5[0,:,:,:] = 1- delP6_345_5[1,:,:,:]


		## next start with delP7_345_x
		##

		delP7_345_3[1,0,0,0] = (-freqall[2]*np.exp(-bindingE[9])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*0.0
				+freqall[3]*np.exp(-bindingE[10])*0.0
				+freqall[4]*np.exp(-bindingE[11])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*0.0))**2)

		delP7_345_3[1,1,0,0] = (-freqall[2]*np.exp(-bindingE[9])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*1.0
				+freqall[3]*np.exp(-bindingE[10])*0.0
				+freqall[4]*np.exp(-bindingE[11])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*0.0))**2)

		delP7_345_3[1,0,1,0] = (-freqall[2]*np.exp(-bindingE[9])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*0.0
				+freqall[3]*np.exp(-bindingE[10])*1.0
				+freqall[4]*np.exp(-bindingE[11])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*0.0))**2)

		delP7_345_3[1,0,0,1] = (-freqall[2]*np.exp(-bindingE[9])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*0.0
				+freqall[3]*np.exp(-bindingE[10])*0.0
				+freqall[4]*np.exp(-bindingE[11])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*1.0))**2)

		delP7_345_3[1,1,1,0] = (-freqall[2]*np.exp(-bindingE[9])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*1.0
				+freqall[3]*np.exp(-bindingE[10])*1.0
				+freqall[4]*np.exp(-bindingE[11])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*0.0))**2)

		delP7_345_3[1,1,0,1] = (-freqall[2]*np.exp(-bindingE[9])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*1.0
				+freqall[3]*np.exp(-bindingE[10])*0.0
				+freqall[4]*np.exp(-bindingE[11])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*1.0))**2)

		delP7_345_3[1,0,1,1] = (-freqall[2]*np.exp(-bindingE[9])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*0.0
				+freqall[3]*np.exp(-bindingE[10])*1.0
				+freqall[4]*np.exp(-bindingE[11])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*1.0))**2)

		delP7_345_3[1,1,1,1] = (-freqall[2]*np.exp(-bindingE[9])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*1.0
				+freqall[3]*np.exp(-bindingE[10])*1.0
				+freqall[4]*np.exp(-bindingE[11])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*1.0))**2)

		delP7_345_3[0,:,:,:] = 1- delP7_345_3[1,:,:,:]


		###
		delP7_345_4[1,0,0,0] = (-freqall[3]*np.exp(-bindingE[10])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*0.0
				+freqall[3]*np.exp(-bindingE[10])*0.0
				+freqall[4]*np.exp(-bindingE[11])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*0.0))**2)

		delP7_345_4[1,1,0,0] = (-freqall[3]*np.exp(-bindingE[10])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*1.0
				+freqall[3]*np.exp(-bindingE[10])*0.0
				+freqall[4]*np.exp(-bindingE[11])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*0.0))**2)

		delP7_345_4[1,0,1,0] = (-freqall[3]*np.exp(-bindingE[10])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*0.0
				+freqall[3]*np.exp(-bindingE[10])*1.0
				+freqall[4]*np.exp(-bindingE[11])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*0.0))**2)

		delP7_345_4[1,0,0,1] = (-freqall[3]*np.exp(-bindingE[10])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*0.0
				+freqall[3]*np.exp(-bindingE[10])*0.0
				+freqall[4]*np.exp(-bindingE[11])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*1.0))**2)

		delP7_345_4[1,1,1,0] = (-freqall[3]*np.exp(-bindingE[10])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*1.0
				+freqall[3]*np.exp(-bindingE[10])*1.0
				+freqall[4]*np.exp(-bindingE[11])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*0.0))**2)

		delP7_345_4[1,1,0,1] = (-freqall[3]*np.exp(-bindingE[10])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*1.0
				+freqall[3]*np.exp(-bindingE[10])*0.0
				+freqall[4]*np.exp(-bindingE[11])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*1.0))**2)

		delP7_345_4[1,0,1,1] = (-freqall[3]*np.exp(-bindingE[10])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*0.0
				+freqall[3]*np.exp(-bindingE[10])*1.0
				+freqall[4]*np.exp(-bindingE[11])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*1.0))**2)

		delP7_345_4[1,1,1,1] = (-freqall[3]*np.exp(-bindingE[10])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*1.0
				+freqall[3]*np.exp(-bindingE[10])*1.0
				+freqall[4]*np.exp(-bindingE[11])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*1.0))**2)

		delP7_345_4[0,:,:,:] = 1- delP7_345_4[1,:,:,:]


		###
		delP7_345_5[1,0,0,0] = (-freqall[4]*np.exp(-bindingE[11])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*0.0
				+freqall[3]*np.exp(-bindingE[10])*0.0
				+freqall[4]*np.exp(-bindingE[11])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*0.0))**2)

		delP7_345_5[1,1,0,0] = (-freqall[4]*np.exp(-bindingE[11])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*1.0
				+freqall[3]*np.exp(-bindingE[10])*0.0
				+freqall[4]*np.exp(-bindingE[11])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*0.0))**2)

		delP7_345_5[1,0,1,0] = (-freqall[4]*np.exp(-bindingE[11])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*0.0
				+freqall[3]*np.exp(-bindingE[10])*1.0
				+freqall[4]*np.exp(-bindingE[11])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*0.0))**2)

		delP7_345_5[1,0,0,1] = (-freqall[4]*np.exp(-bindingE[11])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*0.0
				+freqall[3]*np.exp(-bindingE[10])*0.0
				+freqall[4]*np.exp(-bindingE[11])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*0.0-freqall[4]*1.0))**2)

		delP7_345_5[1,1,1,0] = (-freqall[4]*np.exp(-bindingE[11])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*0.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*1.0
				+freqall[3]*np.exp(-bindingE[10])*1.0
				+freqall[4]*np.exp(-bindingE[11])*0.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*0.0))**2)

		delP7_345_5[1,1,0,1] = (-freqall[4]*np.exp(-bindingE[11])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*1.0
				+freqall[3]*np.exp(-bindingE[10])*0.0
				+freqall[4]*np.exp(-bindingE[11])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*0.0-freqall[4]*1.0))**2)

		delP7_345_5[1,0,1,1] = (-freqall[4]*np.exp(-bindingE[11])*0.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*0.0
				+freqall[3]*np.exp(-bindingE[10])*1.0
				+freqall[4]*np.exp(-bindingE[11])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*0.0-freqall[3]*1.0-freqall[4]*1.0))**2)

		delP7_345_5[1,1,1,1] = (-freqall[4]*np.exp(-bindingE[11])*1.0*(1
				+(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*1.0)*np.exp(-bindingW)))/((1
				+freqall[2]*np.exp(-bindingE[9])*1.0
				+freqall[3]*np.exp(-bindingE[10])*1.0
				+freqall[4]*np.exp(-bindingE[11])*1.0
				+np.exp(-bindingW)*(freqall[2]+freqall[3]+freqall[4]-freqall[2]*1.0-freqall[3]*1.0-freqall[4]*1.0))**2)

		delP7_345_5[0,:,:,:] = 1- delP7_345_5[1,:,:,:]






		


		# next merge delP3_12_1, delP3_12_2 with P(5|12) P(4|12) and P(6|345) and marginalize over x3 x4 x5 to get the 
		# gradient with respect to epsilon_13
		# P3456 = np.zeros((2,2,2,2)) # p(x6|x3 x4 x5)
		#Pa 6 encodes (x3,x4,x5)= 000, 001, 010, 011, 100, 101, 110, 111

		
		fmerge = delP3_12_1[0,0,0]*P3456[:,0,:,:] + delP3_12_1[1,0,0]*P3456[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,0,0]+ fmerge[:,1,:]*P124[1,0,0] #[x6, x5] for (x1, x2) = (0,0) 
		delf612_13[:,0,0] = fmerge[:,0]*P125[0,0,0] + fmerge[:,1]*P125[1,0,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0.0))

		fmerge = delP3_12_1[0,0,1]*P3456[:,0,:,:] + delP3_12_1[1,0,1]*P3456[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,0,1]+ fmerge[:,1,:]*P124[1,0,1] #[x6, x5] for (x1, x2) = (0,1) 
		delf612_13[:,0,1] = fmerge[:,0]*P125[0,0,1] + fmerge[:,1]*P125[1,0,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0, 1))

		fmerge = delP3_12_1[0,1,0]*P3456[:,0,:,:] + delP3_12_1[1,1,0]*P3456[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,1,0]+ fmerge[:,1,:]*P124[1,1,0] #[x6, x5] for (x1, x2) = (1,0) 
		delf612_13[:,1,0] = fmerge[:,0]*P125[0,1,0] + fmerge[:,1]*P125[1,1,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,0))

		fmerge = delP3_12_1[0,1,1]*P3456[:,0,:,:] + delP3_12_1[1,1,1]*P3456[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,1,1]+ fmerge[:,1,:]*P124[1,1,1] #[x6, x5] for (x1, x2) = (1,1) 
		delf612_13[:,1,1] = fmerge[:,0]*P125[0,1,1] + fmerge[:,1]*P125[1,1,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,1))


		# next do the same to get delf612_23
		fmerge = delP3_12_2[0,0,0]*P3456[:,0,:,:] + delP3_12_2[1,0,0]*P3456[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,0,0]+ fmerge[:,1,:]*P124[1,0,0] #[x6, x5] for (x1, x2) = (0,0) 
		delf612_23[:,0,0] = fmerge[:,0]*P125[0,0,0] + fmerge[:,1]*P125[1,0,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0.0))

		fmerge = delP3_12_2[0,0,1]*P3456[:,0,:,:] + delP3_12_2[1,0,1]*P3456[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,0,1]+ fmerge[:,1,:]*P124[1,0,1] #[x6, x5] for (x1, x2) = (0,1) 
		delf612_23[:,0,1] = fmerge[:,0]*P125[0,0,1] + fmerge[:,1]*P125[1,0,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0, 1))

		fmerge = delP3_12_2[0,1,0]*P3456[:,0,:,:] + delP3_12_2[1,1,0]*P3456[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,1,0]+ fmerge[:,1,:]*P124[1,1,0] #[x6, x5] for (x1, x2) = (1,0) 
		delf612_23[:,1,0] = fmerge[:,0]*P125[0,1,0] + fmerge[:,1]*P125[1,1,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,0))

		fmerge = delP3_12_2[0,1,1]*P3456[:,0,:,:] + delP3_12_2[1,1,1]*P3456[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,1,1]+ fmerge[:,1,:]*P124[1,1,1] #[x6, x5] for (x1, x2) = (1,1) 
		delf612_23[:,1,1] = fmerge[:,0]*P125[0,1,1] + fmerge[:,1]*P125[1,1,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,1))


		# next get delf612_14
		###############################
		fmerge = delP4_12_1[0,0,0]*P3456[:,:,0,:] + delP4_12_1[1,0,0]*P3456[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,0,0]+ fmerge[:,1,:]*P123[1,0,0] #[x6, x5] for (x1, x2) = (0,0) 
		delf612_14[:,0,0] = fmerge[:,0]*P125[0,0,0] + fmerge[:,1]*P125[1,0,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0.0))

		fmerge = delP4_12_1[0,0,1]*P3456[:,:,0,:] + delP4_12_1[1,0,1]*P3456[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,0,1]+ fmerge[:,1,:]*P123[1,0,1] #[x6, x5] for (x1, x2) = (0,1) 
		delf612_14[:,0,1] = fmerge[:,0]*P125[0,0,1] + fmerge[:,1]*P125[1,0,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0, 1))

		fmerge = delP4_12_1[0,1,0]*P3456[:,:,0,:] + delP4_12_1[1,1,0]*P3456[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,1,0]+ fmerge[:,1,:]*P123[1,1,0] #[x6, x5] for (x1, x2) = (1,0) 
		delf612_14[:,1,0] = fmerge[:,0]*P125[0,1,0] + fmerge[:,1]*P125[1,1,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,0))

		fmerge = delP4_12_1[0,1,1]*P3456[:,:,0,:] + delP4_12_1[1,1,1]*P3456[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,1,1]+ fmerge[:,1,:]*P123[1,1,1] #[x6, x5] for (x1, x2) = (1,1) 
		delf612_14[:,1,1] = fmerge[:,0]*P125[0,1,1] + fmerge[:,1]*P125[1,1,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,1))


		# next do the same to get delf612_24
		fmerge = delP4_12_2[0,0,0]*P3456[:,:,0,:] + delP4_12_2[1,0,0]*P3456[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,0,0]+ fmerge[:,1,:]*P123[1,0,0] #[x6, x5] for (x1, x2) = (0,0) 
		delf612_24[:,0,0] = fmerge[:,0]*P125[0,0,0] + fmerge[:,1]*P125[1,0,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0.0))

		fmerge = delP4_12_2[0,0,1]*P3456[:,:,0,:] + delP4_12_2[1,0,1]*P3456[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,0,1]+ fmerge[:,1,:]*P123[1,0,1] #[x6, x5] for (x1, x2) = (0,1) 
		delf612_24[:,0,1] = fmerge[:,0]*P125[0,0,1] + fmerge[:,1]*P125[1,0,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0, 1))

		fmerge = delP4_12_2[0,1,0]*P3456[:,:,0,:] + delP4_12_2[1,1,0]*P3456[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,1,0]+ fmerge[:,1,:]*P123[1,1,0] #[x6, x5] for (x1, x2) = (1,0) 
		delf612_24[:,1,0] = fmerge[:,0]*P125[0,1,0] + fmerge[:,1]*P125[1,1,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,0))

		fmerge = delP4_12_2[0,1,1]*P3456[:,:,0,:] + delP4_12_2[1,1,1]*P3456[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,1,1]+ fmerge[:,1,:]*P123[1,1,1] #[x6, x5] for (x1, x2) = (1,1) 
		delf612_24[:,1,1] = fmerge[:,0]*P125[0,1,1] + fmerge[:,1]*P125[1,1,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,1))

		# next get delf612_15
		###############################
		fmerge = delP5_12_1[0,0,0]*P3456[:,:,:,0] + delP5_12_1[1,0,0]*P3456[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,0,0]+ fmerge[:,1,:]*P123[1,0,0] #[x6, x4] for (x1, x2) = (0,0) 
		delf612_15[:,0,0] = fmerge[:,0]*P124[0,0,0] + fmerge[:,1]*P124[1,0,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0.0))

		fmerge = delP5_12_1[0,0,1]*P3456[:,:,:,0] + delP5_12_1[1,0,1]*P3456[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,0,1]+ fmerge[:,1,:]*P123[1,0,1] #[x6, x4] for (x1, x2) = (0,1) 
		delf612_15[:,0,1] = fmerge[:,0]*P124[0,0,1] + fmerge[:,1]*P124[1,0,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0, 1))

		fmerge = delP5_12_1[0,1,0]*P3456[:,:,:,0] + delP5_12_1[1,1,0]*P3456[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,1,0]+ fmerge[:,1,:]*P123[1,1,0] #[x6, x4] for (x1, x2) = (1,0) 
		delf612_15[:,1,0] = fmerge[:,0]*P124[0,1,0] + fmerge[:,1]*P124[1,1,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,0))

		fmerge = delP5_12_1[0,1,1]*P3456[:,:,:,0] + delP5_12_1[1,1,1]*P3456[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,1,1]+ fmerge[:,1,:]*P123[1,1,1] #[x6, x4] for (x1, x2) = (1,1) 
		delf612_15[:,1,1] = fmerge[:,0]*P124[0,1,1] + fmerge[:,1]*P124[1,1,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,1))


		# next do the same to get delf612_25
		fmerge = delP5_12_2[0,0,0]*P3456[:,:,:,0] + delP5_12_2[1,0,0]*P3456[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,0,0]+ fmerge[:,1,:]*P123[1,0,0] #[x6, x4] for (x1, x2) = (0,0) 
		delf612_25[:,0,0] = fmerge[:,0]*P124[0,0,0] + fmerge[:,1]*P124[1,0,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0.0))

		fmerge = delP5_12_2[0,0,1]*P3456[:,:,:,0] + delP5_12_2[1,0,1]*P3456[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,0,1]+ fmerge[:,1,:]*P123[1,0,1] #[x6, x4] for (x1, x2) = (0,1) 
		delf612_25[:,0,1] = fmerge[:,0]*P124[0,0,1] + fmerge[:,1]*P124[1,0,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0, 1))

		fmerge = delP5_12_2[0,1,0]*P3456[:,:,:,0] + delP5_12_2[1,1,0]*P3456[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,1,0]+ fmerge[:,1,:]*P123[1,1,0] #[x6, x4] for (x1, x2) = (1,0) 
		delf612_25[:,1,0] = fmerge[:,0]*P124[0,1,0] + fmerge[:,1]*P124[1,1,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,0))

		fmerge = delP5_12_2[0,1,1]*P3456[:,:,:,0] + delP5_12_2[1,1,1]*P3456[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,1,1]+ fmerge[:,1,:]*P123[1,1,1] #[x6, x4] for (x1, x2) = (1,1) 
		delf612_25[:,1,1] = fmerge[:,0]*P124[0,1,1] + fmerge[:,1]*P124[1,1,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,1))



		###
		# now deal with delf612_36
		####

		gmerge = delP6_345_3[:,0,:,:]*P123[0,0,0] + delP6_345_3[:,1,:,:]*P123[1,0,0] # (x6 x4 x5)
		gmerge = gmerge[:,0,:]*P124[0,0,0] + gmerge[:,1,:]*P124[1,0,0] # (x6 x5)
		delf612_36[:,0,0] = gmerge[:,0]*P125[0,0,0]+ gmerge[:,1]*P125[1,0,0]

		gmerge = delP6_345_3[:,0,:,:]*P123[0,1,0] + delP6_345_3[:,1,:,:]*P123[1,1,0] # (x6 x4 x5)
		gmerge = gmerge[:,0,:]*P124[0,1,0] + gmerge[:,1,:]*P124[1,1,0] # (x6 x5)
		delf612_36[:,1,0] = gmerge[:,0]*P125[0,1,0]+ gmerge[:,1]*P125[1,1,0]

		gmerge = delP6_345_3[:,0,:,:]*P123[0,0,1] + delP6_345_3[:,1,:,:]*P123[1,0,1] # (x6 x4 x5)
		gmerge = gmerge[:,0,:]*P124[0,0,1] + gmerge[:,1,:]*P124[1,0,1] # (x6 x5)
		delf612_36[:,0,1] = gmerge[:,0]*P125[0,0,1]+ gmerge[:,1]*P125[1,0,1]

		gmerge = delP6_345_3[:,0,:,:]*P123[0,1,1] + delP6_345_3[:,1,:,:]*P123[1,1,1] # (x6 x4 x5)
		gmerge = gmerge[:,0,:]*P124[0,1,1] + gmerge[:,1,:]*P124[1,1,1] # (x6 x5)
		delf612_36[:,1,1] = gmerge[:,0]*P125[0,1,1]+ gmerge[:,1]*P125[1,1,1]

		###
		# now deal with delf612_46
		####

		gmerge = delP6_345_4[:,:,0,:]*P124[0,0,0] + delP6_345_4[:,:,1,:]*P124[1,0,0] # (x6 x3 x5)
		gmerge = gmerge[:,0,:]*P123[0,0,0] + gmerge[:,1,:]*P123[1,0,0] # (x6 x5)
		delf612_46[:,0,0] = gmerge[:,0]*P125[0,0,0]+ gmerge[:,1]*P125[1,0,0]

		gmerge = delP6_345_4[:,:,0,:]*P124[0,1,0] + delP6_345_4[:,:,1,:]*P124[1,1,0] # (x6 x3 x5)
		gmerge = gmerge[:,0,:]*P123[0,1,0] + gmerge[:,1,:]*P123[1,1,0] # (x6 x5)
		delf612_46[:,1,0] = gmerge[:,0]*P125[0,1,0]+ gmerge[:,1]*P125[1,1,0]

		gmerge = delP6_345_4[:,:,0,:]*P124[0,0,1] + delP6_345_4[:,:,1,:]*P124[1,0,1] # (x6 x3 x5)
		gmerge = gmerge[:,0,:]*P123[0,0,1] + gmerge[:,1,:]*P123[1,0,1] # (x6 x5)
		delf612_46[:,0,1] = gmerge[:,0]*P125[0,0,1]+ gmerge[:,1]*P125[1,0,1]

		gmerge = delP6_345_4[:,:,0,:]*P124[0,1,1] + delP6_345_4[:,:,1,:]*P124[1,1,1] # (x6 x3 x5)
		gmerge = gmerge[:,0,:]*P123[0,1,1] + gmerge[:,1,:]*P123[1,1,1] # (x6 x5)
		delf612_46[:,1,1] = gmerge[:,0]*P125[0,1,1]+ gmerge[:,1]*P125[1,1,1]


		###
		# now deal with delf612_56
		####

		gmerge = delP6_345_5[:,:,:,0]*P125[0,0,0] + delP6_345_5[:,:,:,1]*P125[1,0,0] # (x6 x3 x4)
		gmerge = gmerge[:,0,:]*P123[0,0,0] + gmerge[:,1,:]*P123[1,0,0] # (x6 x4)
		delf612_56[:,0,0] = gmerge[:,0]*P124[0,0,0]+ gmerge[:,1]*P124[1,0,0]

		gmerge = delP6_345_5[:,:,:,0]*P125[0,1,0] + delP6_345_5[:,:,:,1]*P125[1,1,0] # (x6 x3 x4)
		gmerge = gmerge[:,0,:]*P123[0,1,0] + gmerge[:,1,:]*P123[1,1,0] # (x6 x4)
		delf612_56[:,1,0] = gmerge[:,0]*P124[0,1,0]+ gmerge[:,1]*P124[1,1,0]

		gmerge = delP6_345_5[:,:,:,0]*P125[0,0,1] + delP6_345_5[:,:,:,1]*P125[1,0,1] # (x6 x3 x4)
		gmerge = gmerge[:,0,:]*P123[0,0,1] + gmerge[:,1,:]*P123[1,0,1] # (x6 x4)
		delf612_56[:,0,1] = gmerge[:,0]*P124[0,0,1]+ gmerge[:,1]*P124[1,0,1]

		gmerge = delP6_345_5[:,:,:,0]*P125[0,1,1] + delP6_345_5[:,:,:,1]*P125[1,1,1] # (x6 x3 x4)
		gmerge = gmerge[:,0,:]*P123[0,1,1] + gmerge[:,1,:]*P123[1,1,1] # (x6 x4)
		delf612_56[:,1,1] = gmerge[:,0]*P124[0,1,1]+ gmerge[:,1]*P124[1,1,1]







		### below  deal with the corresponding delf712_xx

		# next merge delP3_12_1, delP3_12_2 with P(5|12) P(4|12) and P(7|345) and marginalize over x3 x4 x5 to get the 
		# gradient with respect to epsilon_13
		# P34567= np.zeros((2,2,2,2)) # p(x7|x3 x4 x5)
		#Pa 6 encodes (x3,x4,x5)= 000, 001, 010, 011, 100, 101, 110, 111

		
		fmerge = delP3_12_1[0,0,0]*P3457[:,0,:,:] + delP3_12_1[1,0,0]*P3457[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,0,0]+ fmerge[:,1,:]*P124[1,0,0] #[x6, x5] for (x1, x2) = (0,0) 
		delf712_13[:,0,0] = fmerge[:,0]*P125[0,0,0] + fmerge[:,1]*P125[1,0,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0.0))

		fmerge = delP3_12_1[0,0,1]*P3457[:,0,:,:] + delP3_12_1[1,0,1]*P3457[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,0,1]+ fmerge[:,1,:]*P124[1,0,1] #[x6, x5] for (x1, x2) = (0,1) 
		delf712_13[:,0,1] = fmerge[:,0]*P125[0,0,1] + fmerge[:,1]*P125[1,0,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0, 1))

		fmerge = delP3_12_1[0,1,0]*P3457[:,0,:,:] + delP3_12_1[1,1,0]*P3457[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,1,0]+ fmerge[:,1,:]*P124[1,1,0] #[x6, x5] for (x1, x2) = (1,0) 
		delf712_13[:,1,0] = fmerge[:,0]*P125[0,1,0] + fmerge[:,1]*P125[1,1,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,0))

		fmerge = delP3_12_1[0,1,1]*P3457[:,0,:,:] + delP3_12_1[1,1,1]*P3457[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,1,1]+ fmerge[:,1,:]*P124[1,1,1] #[x6, x5] for (x1, x2) = (1,1) 
		delf712_13[:,1,1] = fmerge[:,0]*P125[0,1,1] + fmerge[:,1]*P125[1,1,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,1))


		# next do the same to get delf712_23
		fmerge = delP3_12_2[0,0,0]*P3457[:,0,:,:] + delP3_12_2[1,0,0]*P3457[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,0,0]+ fmerge[:,1,:]*P124[1,0,0] #[x6, x5] for (x1, x2) = (0,0) 
		delf712_23[:,0,0] = fmerge[:,0]*P125[0,0,0] + fmerge[:,1]*P125[1,0,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0.0))

		fmerge = delP3_12_2[0,0,1]*P3457[:,0,:,:] + delP3_12_2[1,0,1]*P3457[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,0,1]+ fmerge[:,1,:]*P124[1,0,1] #[x6, x5] for (x1, x2) = (0,1) 
		delf712_23[:,0,1] = fmerge[:,0]*P125[0,0,1] + fmerge[:,1]*P125[1,0,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0, 1))

		fmerge = delP3_12_2[0,1,0]*P3457[:,0,:,:] + delP3_12_2[1,1,0]*P3457[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,1,0]+ fmerge[:,1,:]*P124[1,1,0] #[x6, x5] for (x1, x2) = (1,0) 
		delf712_23[:,1,0] = fmerge[:,0]*P125[0,1,0] + fmerge[:,1]*P125[1,1,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,0))

		fmerge = delP3_12_2[0,1,1]*P3457[:,0,:,:] + delP3_12_2[1,1,1]*P3457[:,1,:,:] # [x6, x4, x5]
		fmerge = fmerge[:,0,:]*P124[0,1,1]+ fmerge[:,1,:]*P124[1,1,1] #[x6, x5] for (x1, x2) = (1,1) 
		delf712_23[:,1,1] = fmerge[:,0]*P125[0,1,1] + fmerge[:,1]*P125[1,1,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,1))


		# next get delf712_14
		###############################
		fmerge = delP4_12_1[0,0,0]*P3457[:,:,0,:] + delP4_12_1[1,0,0]*P3457[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,0,0]+ fmerge[:,1,:]*P123[1,0,0] #[x6, x5] for (x1, x2) = (0,0) 
		delf712_14[:,0,0] = fmerge[:,0]*P125[0,0,0] + fmerge[:,1]*P125[1,0,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0.0))

		fmerge = delP4_12_1[0,0,1]*P3457[:,:,0,:] + delP4_12_1[1,0,1]*P3457[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,0,1]+ fmerge[:,1,:]*P123[1,0,1] #[x6, x5] for (x1, x2) = (0,1) 
		delf712_14[:,0,1] = fmerge[:,0]*P125[0,0,1] + fmerge[:,1]*P125[1,0,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0, 1))

		fmerge = delP4_12_1[0,1,0]*P3457[:,:,0,:] + delP4_12_1[1,1,0]*P3457[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,1,0]+ fmerge[:,1,:]*P123[1,1,0] #[x6, x5] for (x1, x2) = (1,0) 
		delf712_14[:,1,0] = fmerge[:,0]*P125[0,1,0] + fmerge[:,1]*P125[1,1,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,0))

		fmerge = delP4_12_1[0,1,1]*P3457[:,:,0,:] + delP4_12_1[1,1,1]*P3457[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,1,1]+ fmerge[:,1,:]*P123[1,1,1] #[x6, x5] for (x1, x2) = (1,1) 
		delf712_14[:,1,1] = fmerge[:,0]*P125[0,1,1] + fmerge[:,1]*P125[1,1,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,1))


		# next do the same to get delf712_24
		fmerge = delP4_12_2[0,0,0]*P3457[:,:,0,:] + delP4_12_2[1,0,0]*P3457[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,0,0]+ fmerge[:,1,:]*P123[1,0,0] #[x6, x5] for (x1, x2) = (0,0) 
		delf712_24[:,0,0] = fmerge[:,0]*P125[0,0,0] + fmerge[:,1]*P125[1,0,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0.0))

		fmerge = delP4_12_2[0,0,1]*P3457[:,:,0,:] + delP4_12_2[1,0,1]*P3457[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,0,1]+ fmerge[:,1,:]*P123[1,0,1] #[x6, x5] for (x1, x2) = (0,1) 
		delf712_24[:,0,1] = fmerge[:,0]*P125[0,0,1] + fmerge[:,1]*P125[1,0,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0, 1))

		fmerge = delP4_12_2[0,1,0]*P3457[:,:,0,:] + delP4_12_2[1,1,0]*P3457[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,1,0]+ fmerge[:,1,:]*P123[1,1,0] #[x6, x5] for (x1, x2) = (1,0) 
		delf712_24[:,1,0] = fmerge[:,0]*P125[0,1,0] + fmerge[:,1]*P125[1,1,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,0))

		fmerge = delP4_12_2[0,1,1]*P3457[:,:,0,:] + delP4_12_2[1,1,1]*P3457[:,:,1,:] # [x6, x3, x5]
		fmerge = fmerge[:,0,:]*P123[0,1,1]+ fmerge[:,1,:]*P123[1,1,1] #[x6, x5] for (x1, x2) = (1,1) 
		delf712_24[:,1,1] = fmerge[:,0]*P125[0,1,1] + fmerge[:,1]*P125[1,1,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,1))

		# next get delf712_15
		###############################
		fmerge = delP5_12_1[0,0,0]*P3457[:,:,:,0] + delP5_12_1[1,0,0]*P3457[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,0,0]+ fmerge[:,1,:]*P123[1,0,0] #[x6, x4] for (x1, x2) = (0,0) 
		delf712_15[:,0,0] = fmerge[:,0]*P124[0,0,0] + fmerge[:,1]*P124[1,0,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0.0))

		fmerge = delP5_12_1[0,0,1]*P3457[:,:,:,0] + delP5_12_1[1,0,1]*P3457[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,0,1]+ fmerge[:,1,:]*P123[1,0,1] #[x6, x4] for (x1, x2) = (0,1) 
		delf712_15[:,0,1] = fmerge[:,0]*P124[0,0,1] + fmerge[:,1]*P124[1,0,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0, 1))

		fmerge = delP5_12_1[0,1,0]*P3457[:,:,:,0] + delP5_12_1[1,1,0]*P3457[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,1,0]+ fmerge[:,1,:]*P123[1,1,0] #[x6, x4] for (x1, x2) = (1,0) 
		delf712_15[:,1,0] = fmerge[:,0]*P124[0,1,0] + fmerge[:,1]*P124[1,1,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,0))

		fmerge = delP5_12_1[0,1,1]*P3457[:,:,:,0] + delP5_12_1[1,1,1]*P3457[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,1,1]+ fmerge[:,1,:]*P123[1,1,1] #[x6, x4] for (x1, x2) = (1,1) 
		delf712_15[:,1,1] = fmerge[:,0]*P124[0,1,1] + fmerge[:,1]*P124[1,1,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,1))


		# next do the same to get delf712_25
		fmerge = delP5_12_2[0,0,0]*P3457[:,:,:,0] + delP5_12_2[1,0,0]*P3457[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,0,0]+ fmerge[:,1,:]*P123[1,0,0] #[x6, x4] for (x1, x2) = (0,0) 
		delf712_25[:,0,0] = fmerge[:,0]*P124[0,0,0] + fmerge[:,1]*P124[1,0,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0.0))

		fmerge = delP5_12_2[0,0,1]*P3457[:,:,:,0] + delP5_12_2[1,0,1]*P3457[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,0,1]+ fmerge[:,1,:]*P123[1,0,1] #[x6, x4] for (x1, x2) = (0,1) 
		delf712_25[:,0,1] = fmerge[:,0]*P124[0,0,1] + fmerge[:,1]*P124[1,0,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (0, 1))

		fmerge = delP5_12_2[0,1,0]*P3457[:,:,:,0] + delP5_12_2[1,1,0]*P3457[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,1,0]+ fmerge[:,1,:]*P123[1,1,0] #[x6, x4] for (x1, x2) = (1,0) 
		delf712_25[:,1,0] = fmerge[:,0]*P124[0,1,0] + fmerge[:,1]*P124[1,1,0] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,0))

		fmerge = delP5_12_2[0,1,1]*P3457[:,:,:,0] + delP5_12_2[1,1,1]*P3457[:,:,:,1] # [x6, x3, x4]
		fmerge = fmerge[:,0,:]*P123[0,1,1]+ fmerge[:,1,:]*P123[1,1,1] #[x6, x4] for (x1, x2) = (1,1) 
		delf712_25[:,1,1] = fmerge[:,0]*P124[0,1,1] + fmerge[:,1]*P124[1,1,1] # del P(6|1,2)/ del epsilon_{13} at (x1, x2) = (1,1))



		###hhhh
		# now deal with delf712_37
		####

		gmerge = delP7_345_3[:,0,:,:]*P123[0,0,0] + delP7_345_3[:,1,:,:]*P123[1,0,0] # (x6 x4 x5)
		gmerge = gmerge[:,0,:]*P124[0,0,0] + gmerge[:,1,:]*P124[1,0,0] # (x6 x5)
		delf712_37[:,0,0] = gmerge[:,0]*P125[0,0,0]+ gmerge[:,1]*P125[1,0,0]

		gmerge = delP7_345_3[:,0,:,:]*P123[0,1,0] + delP7_345_3[:,1,:,:]*P123[1,1,0] # (x6 x4 x5)
		gmerge = gmerge[:,0,:]*P124[0,1,0] + gmerge[:,1,:]*P124[1,1,0] # (x6 x5)
		delf712_37[:,1,0] = gmerge[:,0]*P125[0,1,0]+ gmerge[:,1]*P125[1,1,0]

		gmerge = delP7_345_3[:,0,:,:]*P123[0,0,1] + delP7_345_3[:,1,:,:]*P123[1,0,1] # (x6 x4 x5)
		gmerge = gmerge[:,0,:]*P124[0,0,1] + gmerge[:,1,:]*P124[1,0,1] # (x6 x5)
		delf712_37[:,0,1] = gmerge[:,0]*P125[0,0,1]+ gmerge[:,1]*P125[1,0,1]

		gmerge = delP7_345_3[:,0,:,:]*P123[0,1,1] + delP7_345_3[:,1,:,:]*P123[1,1,1] # (x6 x4 x5)
		gmerge = gmerge[:,0,:]*P124[0,1,1] + gmerge[:,1,:]*P124[1,1,1] # (x6 x5)
		delf712_37[:,1,1] = gmerge[:,0]*P125[0,1,1]+ gmerge[:,1]*P125[1,1,1]

		###
		# now deal with delf712_47
		####

		gmerge = delP7_345_4[:,:,0,:]*P124[0,0,0] + delP7_345_4[:,:,1,:]*P124[1,0,0] # (x6 x3 x5)
		gmerge = gmerge[:,0,:]*P123[0,0,0] + gmerge[:,1,:]*P123[1,0,0] # (x6 x5)
		delf712_47[:,0,0] = gmerge[:,0]*P125[0,0,0]+ gmerge[:,1]*P125[1,0,0]

		gmerge = delP7_345_4[:,:,0,:]*P124[0,1,0] + delP7_345_4[:,:,1,:]*P124[1,1,0] # (x6 x3 x5)
		gmerge = gmerge[:,0,:]*P123[0,1,0] + gmerge[:,1,:]*P123[1,1,0] # (x6 x5)
		delf712_47[:,1,0] = gmerge[:,0]*P125[0,1,0]+ gmerge[:,1]*P125[1,1,0]

		gmerge = delP7_345_4[:,:,0,:]*P124[0,0,1] + delP7_345_4[:,:,1,:]*P124[1,0,1] # (x6 x3 x5)
		gmerge = gmerge[:,0,:]*P123[0,0,1] + gmerge[:,1,:]*P123[1,0,1] # (x6 x5)
		delf712_47[:,0,1] = gmerge[:,0]*P125[0,0,1]+ gmerge[:,1]*P125[1,0,1]

		gmerge = delP7_345_4[:,:,0,:]*P124[0,1,1] + delP7_345_4[:,:,1,:]*P124[1,1,1] # (x6 x3 x5)
		gmerge = gmerge[:,0,:]*P123[0,1,1] + gmerge[:,1,:]*P123[1,1,1] # (x6 x5)
		delf712_47[:,1,1] = gmerge[:,0]*P125[0,1,1]+ gmerge[:,1]*P125[1,1,1]


		###
		# now deal with delf712_57
		####

		gmerge = delP7_345_5[:,:,:,0]*P125[0,0,0] + delP7_345_5[:,:,:,1]*P125[1,0,0] # (x6 x3 x4)
		gmerge = gmerge[:,0,:]*P123[0,0,0] + gmerge[:,1,:]*P123[1,0,0] # (x6 x4)
		delf712_57[:,0,0] = gmerge[:,0]*P124[0,0,0]+ gmerge[:,1]*P124[1,0,0]

		gmerge = delP7_345_5[:,:,:,0]*P125[0,1,0] + delP7_345_5[:,:,:,1]*P125[1,1,0] # (x6 x3 x4)
		gmerge = gmerge[:,0,:]*P123[0,1,0] + gmerge[:,1,:]*P123[1,1,0] # (x6 x4)
		delf712_57[:,1,0] = gmerge[:,0]*P124[0,1,0]+ gmerge[:,1]*P124[1,1,0]

		gmerge = delP7_345_5[:,:,:,0]*P125[0,0,1] + delP7_345_5[:,:,:,1]*P125[1,0,1] # (x6 x3 x4)
		gmerge = gmerge[:,0,:]*P123[0,0,1] + gmerge[:,1,:]*P123[1,0,1] # (x6 x4)
		delf712_57[:,0,1] = gmerge[:,0]*P124[0,0,1]+ gmerge[:,1]*P124[1,0,1]

		gmerge = delP7_345_5[:,:,:,0]*P125[0,1,1] + delP7_345_5[:,:,:,1]*P125[1,1,1] # (x6 x3 x4)
		gmerge = gmerge[:,0,:]*P123[0,1,1] + gmerge[:,1,:]*P123[1,1,1] # (x6 x4)
		delf712_57[:,1,1] = gmerge[:,0]*P124[0,1,1]+ gmerge[:,1]*P124[1,1,1]


		tmp = np.array(list(itertools.product([[0],[1]], repeat = 4)))
		Ptemp1 = np.zeros((2,2,2,2))
		Ptemp2 = np.zeros((2,2,2,2))
		Ptemp3 = np.zeros((2,2,2,2))
		Ptemp4 = np.zeros((2,2,2,2))
		Ptemp5 = np.zeros((2,2,2,2))
		Ptemp6 = np.zeros((2,2,2,2))
		Ptemp7 = np.zeros((2,2,2,2))
		Ptemp8 = np.zeros((2,2,2,2))
		Ptemp9 = np.zeros((2,2,2,2))
		Ptemp10 = np.zeros((2,2,2,2))
		Ptemp11 = np.zeros((2,2,2,2))
		Ptemp12 = np.zeros((2,2,2,2))
		for j in xrange(tmp.shape[0]):
			i6 = tmp[j][0][0]
			i7 = tmp[j][1][0]
			i1 = tmp[j][2][0]
			i2 = tmp[j][3][0]

			Ptemp1[i6, i7, i1, i2] = (delf612_13[i6,i1,i2]*P712[i7,i1,i2]+ delf712_13[i7,i1,i2]*P612[i6,i1,i2])*\
			(np.log2(P712[i7,i1,i2])+ np.log2(P612[i6,i1,i2])-np.log2(P67joint[i6,i7]) +1) 

			Ptemp2[i6, i7, i1, i2] = (delf612_23[i6,i1,i2]*P712[i7,i1,i2]+ delf712_23[i7,i1,i2]*P612[i6,i1,i2])*\
			(np.log2(P712[i7,i1,i2])+ np.log2(P612[i6,i1,i2])-np.log2(P67joint[i6,i7]) +1) 

			Ptemp3[i6, i7, i1, i2] = (delf612_14[i6,i1,i2]*P712[i7,i1,i2]+ delf712_14[i7,i1,i2]*P612[i6,i1,i2])*\
			(np.log2(P712[i7,i1,i2])+ np.log2(P612[i6,i1,i2])-np.log2(P67joint[i6,i7]) +1) 

			Ptemp4[i6, i7, i1, i2] = (delf612_24[i6,i1,i2]*P712[i7,i1,i2]+ delf712_24[i7,i1,i2]*P612[i6,i1,i2])*\
			(np.log2(P712[i7,i1,i2])+ np.log2(P612[i6,i1,i2])-np.log2(P67joint[i6,i7]) +1)

			Ptemp5[i6, i7, i1, i2] = (delf612_15[i6,i1,i2]*P712[i7,i1,i2]+ delf712_15[i7,i1,i2]*P612[i6,i1,i2])*\
			(np.log2(P712[i7,i1,i2])+ np.log2(P612[i6,i1,i2])-np.log2(P67joint[i6,i7]) +1) 

			Ptemp6[i6, i7, i1, i2] = (delf612_25[i6,i1,i2]*P712[i7,i1,i2]+ delf712_25[i7,i1,i2]*P612[i6,i1,i2])*\
			(np.log2(P712[i7,i1,i2])+ np.log2(P612[i6,i1,i2])-np.log2(P67joint[i6,i7]) +1)

			Ptemp7[i6, i7, i1, i2] = (delf612_36[i6,i1,i2]*P712[i7,i1,i2])*\
			(np.log2(P712[i7,i1,i2])+ np.log2(P612[i6,i1,i2])-np.log2(P67joint[i6,i7]) +1)

			Ptemp8[i6, i7, i1, i2] = (delf612_46[i6,i1,i2]*P712[i7,i1,i2])*\
			(np.log2(P712[i7,i1,i2])+ np.log2(P612[i6,i1,i2])-np.log2(P67joint[i6,i7]) +1)

			Ptemp9[i6, i7, i1, i2] = (delf612_56[i6,i1,i2]*P712[i7,i1,i2])*\
			(np.log2(P712[i7,i1,i2])+ np.log2(P612[i6,i1,i2])-np.log2(P67joint[i6,i7]) +1)

			Ptemp10[i6, i7, i1, i2] = (delf712_37[i7,i1,i2]*P612[i6,i1,i2])*\
			(np.log2(P712[i7,i1,i2])+ np.log2(P612[i6,i1,i2])-np.log2(P67joint[i6,i7]) +1)

			Ptemp11[i6, i7, i1, i2] = (delf712_47[i7,i1,i2]*P612[i6,i1,i2])*\
			(np.log2(P712[i7,i1,i2])+ np.log2(P612[i6,i1,i2])-np.log2(P67joint[i6,i7]) +1)

			Ptemp12[i6, i7, i1, i2] = (delf712_57[i7,i1,i2]*P612[i6,i1,i2])*\
			(np.log2(P712[i7,i1,i2])+ np.log2(P612[i6,i1,i2])-np.log2(P67joint[i6,i7]) +1)





		nabla_E[0] = np.sum(np.sum(np.sum(Ptemp1, axis = 0), axis = 0)*P12)
		nabla_E[1] = np.sum(np.sum(np.sum(Ptemp2, axis = 0), axis = 0)*P12)
		nabla_E[2] = np.sum(np.sum(np.sum(Ptemp3, axis = 0), axis = 0)*P12)
		nabla_E[3] = np.sum(np.sum(np.sum(Ptemp4, axis = 0), axis = 0)*P12)
		nabla_E[4] = np.sum(np.sum(np.sum(Ptemp5, axis = 0), axis = 0)*P12)
		nabla_E[5] = np.sum(np.sum(np.sum(Ptemp6, axis = 0), axis = 0)*P12)
		nabla_E[6] = np.sum(np.sum(np.sum(Ptemp7, axis = 0), axis = 0)*P12)
		nabla_E[7] = np.sum(np.sum(np.sum(Ptemp8, axis = 0), axis = 0)*P12)
		nabla_E[8] = np.sum(np.sum(np.sum(Ptemp9, axis = 0), axis = 0)*P12)
		nabla_E[9] = np.sum(np.sum(np.sum(Ptemp10, axis = 0), axis = 0)*P12)
		nabla_E[10] = np.sum(np.sum(np.sum(Ptemp11, axis = 0), axis = 0)*P12)
		nabla_E[11] = np.sum(np.sum(np.sum(Ptemp12, axis = 0), axis = 0)*P12)




		# bindingE[i]: i = 0, 1 (E31, E32, ngb of 3)
		#			       2, 3 (E41, E42, nbg of 4)
		#				   4, 5 (E51, E52, nbg of 5)
		#				   6, 7,  8  (E63, E64, E65, nbg of 6)
		#				   9, 10, 11 (E73, E74, E75, nbg of 7)

	return nabla_E
			



def SGD(self, training_data, epochs, mini_batch_size, eta,
			test_data=None):
	"""Train the neural network using mini-batch stochastic
	gradient descent.  The ``training_data`` is a list of tuples
	``(x, y)`` representing the training inputs and the desired
	outputs.  The other non-optional parameters are
	self-explanatory.  If ``test_data`` is provided then the
	network will be evaluated against the test data after each
	epoch, and partial progress printed out.  This is useful for
	tracking progress, but slows things down substantially."""
	if test_data: n_test = len(test_data)
	n = len(training_data)
	for j in xrange(epochs):
		random.shuffle(training_data)
		mini_batches = [
			training_data[k:k+mini_batch_size]
			for k in xrange(0, n, mini_batch_size)]
		for mini_batch in mini_batches:
			[W, allbias] = self.update_mini_batch(mini_batch, eta)
		if test_data:
			print "Epoch {0}: {1} / {2}".format(
				j, self.evaluate(test_data), n_test)
		else:
			print "Epoch {0} complete".format(j)
	return [W, allbias]



def update_mini_batch(self, mini_batch, eta):

	"""Update the network's weights and biases by applying
	gradient descent using backpropagation to a single mini batch.
	The ``mini_batch`` is a list of tuples ``(x, y)``, and ``eta``
	is the learning rate."""
	nabla_b = [np.zeros(b.shape) for b in self.biases]
	nabla_w = [np.zeros(w.shape) for w in self.weights]
	for x, y in mini_batch:
		delta_nabla_b, delta_nabla_w = self.backprop(x, y)
		nabla_b = [nb+dnb for nb, dnb in zip(nabla_b, delta_nabla_b)]
		nabla_w = [nw+dnw for nw, dnw in zip(nabla_w, delta_nabla_w)]
	self.weights = [w-(eta/len(mini_batch))*nw 
					for w, nw in zip(self.weights, nabla_w)]
	self.biases = [b-(eta/len(mini_batch))*nb 
					for b, nb in zip(self.biases, nabla_b)]

	return [self.weights, self.biases]



def create_name(learning_rate, reg_level, gdstep):
	
	str_r = 'InfoMax231AllInput' + str(learning_rate) +'_reg_levelC' + str(reg_level) + '_GDsteps'+ repr(gdstep) 

	return str_r


"""end of function specification"""





# Here are some parameters for learning and target function specification

#learning_eta = float(sys.argv[1])  # argument i in the batch file
#regularization = float(sys.argv[2]) # argument j in the batch file
#learning_eta = 0.025 
regularization = 0.0
learning_eta = 0.1
NGD= 100 # Gradient descent steps






# File I/O
dir_name='./'
case_num = 2 # for data manipulation 1 for uniform mu 


# First specify the initial binding affinities
Nproteins = 7
wrong_binding = 2.0  # This can be incorporated into learning

Pinput1 = (np.array([[0.8],[0.2]]), np.array([[0.68],[0.32]]), np.array([[0.6],[0.4]]), np.array([[0.2],[0.8]]))
Pinput2 = (np.array([[0.8],[0.2]]), np.array([[0.68],[0.32]]), np.array([[0.6],[0.4]]), np.array([[0.2],[0.8]]))

#Ebind = 2.0*np.array([-4.0,-4.0,-4.0,-5.0 ,-3.7,-5.62,-1.2,-1.3, -1.8])
Ebind = -3.0+ np.zeros((1,12))
Ebindall = np.zeros((NGD+1, 12, len(Pinput1)), dtype = float)
MI = np.zeros((NGD, len(Pinput1)), dtype = float)




# here for chemical potential mu_i = - log omega_i
# for uniform case, set omega3= Nproteins

omegavec = np.zeros(Nproteins) + Nproteins  # homogenous
mu = - np.log(omegavec) # chemical potential


marginal6 = np.zeros([2,1]) # output
marginal7 = np.zeros([2,1])




# Start main loop



for inputProb in xrange(len(Pinput1)):

	Ebindall[0,:, inputProb] = Ebind


	for ind in xrange(NGD):

		G = Graph()
		x1 = G.addVarNode('x1',2)
		x2 = G.addVarNode('x2',2)
		x3 = G.addVarNode('x3',2)
		x4 = G.addVarNode('x4',2)
		x5 = G.addVarNode('x5',2)
		x6 = G.addVarNode('x6',2)
		x7 = G.addVarNode('x7',2)
	
	

		# Pa3, Pa4, Pa5 encodes (x1,x2)=(0,0), (0,1), (1,0), (1,1)

		Pa3 = np.array(list(itertools.product([[0],[1]], repeat = 2))) # repeat= |pa(x3)| 
		Pa4 = np.array(list(itertools.product([[0],[1]], repeat = 2))) # repeat= |pa(x3)| 
		Pa5 = np.array(list(itertools.product([[0],[1]], repeat = 2))) # repeat= |pa(x3)| 
			
		# Pa6, Pa7 encodes (x3,x4,x5)= 000, 001, 010, 011, 100, 101, 110, 111, shape=8,3,1
		Pa6 = np.array(list(itertools.product([[0],[1]], repeat = 3)))
		Pa7 = np.array(list(itertools.product([[0],[1]], repeat = 3)))
		

		#P1 = np.array([[0.8],[0.2]])  # p(x1)=[p(x1=0), p(x1=1)]
		P1 = Pinput1[inputProb] # assuming flat prior
		G.addFacNode(P1, x1)

		#P2 = np.array([[0.7],[0.3]])  # p(x2)
		P2 = Pinput2[inputProb] # assuming flat prior
		G.addFacNode(P2, x2)



		E3 = Ebindall[ind, 0:2, inputProb] # i.e. E13 E23, ngb of x3
		E4 = Ebindall[ind, 2:4, inputProb] # i.e. E14 E24, ngb of x4
		E5 = Ebindall[ind, 4:6, inputProb] # i.e. E15 E25, ngb of x5
		E6 = Ebindall[ind, 6:9, inputProb] # i.e. E36 E46 E56, ngb of x6
		E7 = Ebindall[ind, 9:12, inputProb] # i.e. E36 E46 E56, ngb of x6
		
		
			
		# note the syntax: conditional_prob_on(PAstate, Ematrix, Wbind, omega):


		# below for factor node P123
		P123 = np.zeros((2,2,2)) # [ p(x3=0|x1 x2), p(x3=1|x1 x2)]
		P123[:,0,0]=[1-conditional_prob_on(Pa3[0], E3, wrong_binding, omegavec[0:2]), conditional_prob_on(Pa3[0], E3, wrong_binding, omegavec[0:2])]
		P123[:,0,1]=[1-conditional_prob_on(Pa3[1], E3, wrong_binding, omegavec[0:2]), conditional_prob_on(Pa3[1], E3, wrong_binding, omegavec[0:2])]
		P123[:,1,0]=[1-conditional_prob_on(Pa3[2], E3, wrong_binding, omegavec[0:2]), conditional_prob_on(Pa3[2], E3, wrong_binding, omegavec[0:2])]
		P123[:,1,1]=[1-conditional_prob_on(Pa3[3], E3, wrong_binding, omegavec[0:2]), conditional_prob_on(Pa3[3], E3, wrong_binding, omegavec[0:2])]


		G.addFacNode(P123,x3,x1,x2)

		# below for factor node P124
		P124 = np.zeros((2,2,2)) # p(x4|x1 x2)
		P124[:,0,0]=[1-conditional_prob_on(Pa4[0], E4, wrong_binding, omegavec[0:2]), conditional_prob_on(Pa4[0], E4, wrong_binding, omegavec[0:2])]
		P124[:,0,1]=[1-conditional_prob_on(Pa4[1], E4, wrong_binding, omegavec[0:2]), conditional_prob_on(Pa4[1], E4, wrong_binding, omegavec[0:2])]
		P124[:,1,0]=[1-conditional_prob_on(Pa4[2], E4, wrong_binding, omegavec[0:2]), conditional_prob_on(Pa4[2], E4, wrong_binding, omegavec[0:2])]
		P124[:,1,1]=[1-conditional_prob_on(Pa4[3], E4, wrong_binding, omegavec[0:2]), conditional_prob_on(Pa4[3], E4, wrong_binding, omegavec[0:2])]


		G.addFacNode(P124,x4,x1,x2)

		# below for factor node P125
		P125 = np.zeros((2,2,2)) # p(x5|x1 x2)
		P125[:,0,0]=[1-conditional_prob_on(Pa5[0], E5, wrong_binding, omegavec[0:2]), conditional_prob_on(Pa5[0], E5, wrong_binding, omegavec[0:2])]
		P125[:,0,1]=[1-conditional_prob_on(Pa5[1], E5, wrong_binding, omegavec[0:2]), conditional_prob_on(Pa5[1], E5, wrong_binding, omegavec[0:2])]
		P125[:,1,0]=[1-conditional_prob_on(Pa5[2], E5, wrong_binding, omegavec[0:2]), conditional_prob_on(Pa5[2], E5, wrong_binding, omegavec[0:2])]
		P125[:,1,1]=[1-conditional_prob_on(Pa5[3], E5, wrong_binding, omegavec[0:2]), conditional_prob_on(Pa5[3], E5, wrong_binding, omegavec[0:2])]


		G.addFacNode(P125,x5,x1,x2)



		P3456 = np.zeros((2,2,2,2)) # p(x6|x3 x4 x5)
		P3457 = np.zeros((2,2,2,2)) # P(x7|x3 x4 x5)
		for i in xrange(Pa6.shape[0]):
			i3 = Pa6[i][0][0]
			i4 = Pa6[i][1][0]
			i5 = Pa6[i][2][0]

			P3456[:,i3,i4,i5] = [1-conditional_prob_on(Pa6[i], E6, wrong_binding, omegavec[2:5]), conditional_prob_on(Pa6[i], E6, wrong_binding, omegavec[2:5])]
			P3457[:,i3,i4,i5] = [1-conditional_prob_on(Pa7[i], E7, wrong_binding, omegavec[2:5]), conditional_prob_on(Pa7[i], E7, wrong_binding, omegavec[2:5])]

		G.addFacNode(P3456,x6,x3,x4,x5)
		G.addFacNode(P3457,x7,x3,x4,x5)


		

		brute = G.bruteForce()
		distx6 = G.marginalizeBrute(brute, 'x6')
		distx7 = G.marginalizeBrute(brute, 'x7')
		
			
		marginal6[0]= float(distx6[0]) # x6 off
		marginal6[1]= float(distx6[1]) # x6 on

		marginal7[0]= float(distx7[0]) # x6 off
		marginal7[1]= float(distx7[1]) # x6 on


	

		# Calculate P612 = P(x6| x1 x2). 
		tmp = np.array(list(itertools.product([[0],[1]], repeat = 6)))
		P6jointcond12 = np.zeros((2,2,2,2,2,2))
		P7jointcond12 = np.zeros((2,2,2,2,2,2))
		P67jointcond12 = np.zeros((2,2,2,2,2,2,2))
		for i in xrange(tmp.shape[0]):
			i1 = tmp[i][0][0] # index for x1
			i2 = tmp[i][1][0] # index for x2
			i3 = tmp[i][2][0] # index for x3
			i4 = tmp[i][3][0] # index for x4
			i5 = tmp[i][4][0] # index for x5
			ilast = tmp[i][5][0] # index for x6 and x7
			P6jointcond12[ilast,i5,i4,i3,i1,i2] = P3456[ilast,i3,i4,i5]*P123[i3,i1,i2]*P124[i4,i1,i2]*P125[i5,i1,i2]
			P7jointcond12[ilast,i5,i4,i3,i1,i2] = P3457[ilast,i3,i4,i5]*P123[i3,i1,i2]*P124[i4,i1,i2]*P125[i5,i1,i2]
			P67jointcond12[ilast,0,i5,i4,i3,i1,i2] = P3456[ilast,i3,i4,i5]*P3457[0,i3,i4,i5]*P123[i3,i1,i2]*P124[i4,i1,i2]*P125[i5,i1,i2]
			P67jointcond12[ilast,1,i5,i4,i3,i1,i2] = P3456[ilast,i3,i4,i5]*P3457[1,i3,i4,i5]*P123[i3,i1,i2]*P124[i4,i1,i2]*P125[i5,i1,i2]



		for i in xrange(3):
			tmp = np.sum(P6jointcond12, axis = 1)
			P6jointcond12 = tmp

			tmp2 = np.sum(P7jointcond12, axis =1)
			P7jointcond12 = tmp

			tmp3 = np.sum(P67jointcond12, axis = 2)
			P67jointcond12 = tmp3

		P612 = P6jointcond12
		P712 = P7jointcond12
		P67cond12 = P67jointcond12 # P(x6 x7| x1 x2)
		
		
		
		P12 = np.outer(P1,P2)
		P612joint = np.zeros((2,2,2)) # P(x6 x1 x2)
		P712joint = np.zeros((2,2,2)) # P(x7 x1 x2)
		P1267 = np.zeros((2,2,2,2)) # P(x6 x7 x1 x2)

		
		tmp = np.array(list(itertools.product([[0],[1]], repeat = 2)))
		for i in xrange(tmp.shape[0]):
			i1 = tmp[i][0][0]
			i2 = tmp[i][1][0]
			P612joint[0,i1,i2] = P612[0,i1,i2]*P12[i1,i2]
			P612joint[1,i1,i2] = P612[1,i1,i2]*P12[i1,i2]

			P712joint[0,i1,i2] = P712[0,i1,i2]*P12[i1,i2]
			P712joint[1,i1,i2] = P712[1,i1,i2]*P12[i1,i2]

			P1267[0,0,i1,i2] = P67cond12[0,0,i1,i2]*P12[i1,i2]
			P1267[0,1,i1,i2] = P67cond12[0,1,i1,i2]*P12[i1,i2]
			P1267[1,0,i1,i2] = P67cond12[1,0,i1,i2]*P12[i1,i2]
			P1267[1,1,i1,i2] = P67cond12[1,1,i1,i2]*P12[i1,i2]






		P6 = np.sum(np.sum(P612joint, axis = 1), axis = 1)
		P7 = np.sum(np.sum(P712joint, axis = 1), axis = 1)
		P67joint = np.zeros((2,2)) 
		P67joint = np.sum(np.sum(P1267, axis = 2), axis = 2) # P(x6, x7)
		
		
		P612 = P6jointcond12 + 1e-8
		P712 = P7jointcond12 + 1e-8
		P67joint = P67joint + 1e-8
		P67cond12 = P67cond12 + 1e-8

		tmp = np.array(list(itertools.product([[0],[1]], repeat = 2)))
		Ptemp = np.zeros((2,2,2,2)) # term in MI that involves P(out|in), note the notation (x6 x7 x1 x2)
		for i in xrange(tmp.shape[0]):
			i1 = tmp[i][0][0] # index for x1
			i2 = tmp[i][1][0] # index for x2
			Ptemp[:,:, i1, i2] = P67cond12[:,:,i1,i2]*np.log2(P67cond12[:,:,i1,i2]/P67joint)
		


		Ptemp = np.sum(np.sum(Ptemp, axis = 0), axis = 0) # trace over x6 x7
		MI[ind, inputProb] = np.sum(Ptemp*P12) # multiply by P12 and trace over x1 x2

		
		Ebindall[ind+1,:, inputProb] = Ebindall[ind, :, inputProb] - learning_eta*InfoMaxGD(P1, P2, P612, P67joint, P3456, P123, P124, P125, Ebindall[ind, :, inputProb], wrong_binding, omegavec, regularization)
		G.reset()	
		




#print MI.shape
#print MI
print Ebindall[NGD,: ,len(Pinput1)-1]

MImax = np.amax(MI, axis=0)

print MImax
file_name = create_name(learning_eta, regularization, NGD) 
name = os.path.join(dir_name, file_name)
pickle.dump( {'BindingEnergy':Ebindall, 'MIall': MI, 'MImax': MImax}, open(name, 'wb'))


			




#print MI.shape
#print Ebindall

runtick = np.linspace(1,NGD, num=NGD)
plt.plot(runtick, MI[:,0], runtick, MI[:,1], '--',runtick, MI[:,2], runtick, MI[:,3],  linewidth=3.0)
plt.xlabel('Gradient ascent runs', fontsize = fl+4)
plt.ylabel('Mutual Information $MI(x_{in};\, x_6)$', fontsize = fl+4)
plt.xticks(fontsize = ft+4)
plt.yticks(fontsize = ft+4)
plt.legend([r'$P(x_{{in}}=1)=0.2$', r'$P(x_{{in}}=1)=0.32$', r'$P(x_{{in}}=1)=0.4$', r'$P(x_{{in}}=1)=0.8$'], shadow=True, fancybox=True, loc=(0.5, 0.3), fontsize=14+2)
plt.show()

#plt.show(block = True)
'''
full_str = 'InfoMax231LearningCurve'
fig_name = os.path.join(dir_name, full_str )
fig.savefig(fig_name+'.eps', bbox_inches='tight')
#fig.savefig(fig_name+'.eps')
#fig.savefig(fig_name+'.png')
#fig.savefig(fig_name+'.pdf', bbox_inches='tight')
fig.savefig(fig_name+'.pdf')
#fig.savefig(fig_name+'.eps')

'''


